blob:
  max_area: 50000
  min_area: 50
  min_circularity: 0.4
camera:
  extended_disparity: false
  fps: 30
  left_right_check: true
  median_filter: 7
  preset_mode: FAST_ACCURACY
  resolution_h: 360
  resolution_w: 640
  subpixel: true
communication:
  esp32_ip: 10.252.108.237
  esp32_port: 12345
  pc_ip: 192.168.137.1
  plot_udp_port: 5006
  wifi_pass: '12345678'
  wifi_ssid: MCE14
extrinsics:
  R:
  - - 1.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 1.0
  - - 0.0
    - -1.0
    - 0.0
  T:
  - 0.0
  - 0.0
  - 0.8548341045067113
filter:
  window_size: 7
hsv:
  lower_red_1:
  - 0
  - 100
  - 80
  lower_red_2:
  - 170
  - 100
  - 80
  upper_red_1:
  - 10
  - 255
  - 255
  upper_red_2:
  - 180
  - 255
  - 255
predictor:
  drag_correction: 0.92
  min_points: 3
  workspace_radius_m: 0.5
  z_catch: 0.25
release:
  displacement_threshold_m: 0.15
  max_transmission_delay_s: 1.0
  vel_threshold: 1.5
robot_tracker:
  lower_gold:
  - 15
  - 80
  - 80
  max_area: 50000
  min_area: 100
  upper_gold:
  - 35
  - 255
  - 255
system:
  camera_max_retries: 5
  camera_retry_delay_s: 2.0
  depth_color_subsample: 6
  max_missing_frames: 15
  robot_tracking_subsample: 15
