blob:
  max_area: 50000
  min_area: 50
  min_circularity: 0.4
camera:
  depth_max_mm: 6000
  depth_min_mm: 200
  extended_disparity: false
  fps: 30
  left_right_check: true
  median_filter: 5
  preset_mode: FAST_ACCURACY
  resolution_h: 360
  resolution_w: 640
  subpixel: true
  vpu_spatial_filter: true
  vpu_temporal_filter: true
communication:
  esp32_ip: 192.168.0.122
  esp32_port: 12345
  pc_ip: 192.168.1.10
  plot_udp_port: 5006
  wifi_pass: '12345678'
  wifi_ssid: MCE14
extrinsics:
  R:
  - - 1.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 1.0
  - - 0.0
    - -1.0
    - 0.0
  T:
  - 0.0
  - 0.0
  - 0.6259642846839569
filter:
  window_size: 5
hsv:
  lower_red_1:
  - 0
  - 100
  - 80
  lower_red_2:
  - 170
  - 100
  - 80
  upper_red_1:
  - 10
  - 255
  - 255
  upper_red_2:
  - 180
  - 255
  - 255
predictor:
  drag_correction: 0.92
  min_points: 3
  workspace_radius_m: 0.5
  z_catch: 0.25
release:
  displacement_threshold_m: 0.1
  max_transmission_delay_s: 1.0
  skin_lower:
  - 5
  - 40
  - 80
  skin_ratio_threshold: 0.08
  skin_upper:
  - 25
  - 255
  - 255
  skin_vel_threshold: 0.5
  vel_threshold: 1.2
robot_tracker:
  lower_green:
  - 35
  - 60
  - 60
  max_area: 50000
  min_area: 100
  upper_green:
  - 85
  - 255
  - 255
system:
  camera_max_retries: 5
  camera_retry_delay_s: 2.0
  depth_color_subsample: 6
  headless: false
  max_missing_frames: 15
  robot_tracking_subsample: 15
